### PR TITLE
feat: eslint

### PR DESCRIPTION
**Pull request by falkenhawk**
This pull request introduces ESLint as the main linting tool in the coding-standard package, replacing TSLint which has been deprecated for many years already.

below are copied contents from updated README.md:

---

## Install

```sh
# using npm
npm install --save-dev @ovos-media/coding-standard

# using yarn
yarn add --dev @ovos-media/coding-standard
```

### `eslint.config.js`

```js
const eslint = require('@ovos-media/coding-standard/eslint');

module.exports = eslint();
```

The configuration is based on the recommended rulesets from [ESLint](https://eslint.org/) and [typescript-eslint](https://typescript-eslint.io/).

It also includes [ESLint Stylistic](https://eslint.style/) which replaces deprecated rules from eslint and typescript-eslint.

Currently, it uses ESLint v8 and typescript-eslint v6.
The upgrade to ESLint v9 and typescript-eslint v7 is planned for the next major release.

`@ovos-media/coding-standard/eslint` exports a function that accepts an object with the following options:

- `console`: `ban`, `ban-log` or `allow` - whether to ban or allow console usage. Defaults to:
  - `ban-log` (which only allows `console.error()`, `console.warn()` and `console.info()`) when `react: true`,
  - `allow` otherwise.
- `disableTypeChecked`: List ts files which should be linted, but are not covered by `tsconfig.json` 
  to avoid `Parsing error (...) TSConfig does not include this file`. [read more &raquo;](https://typescript-eslint.io/linting/troubleshooting/#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file)
  Example: `['dangerfile.ts', '.storybook/*.ts?(x)']`
- `indent` (default: `2`): number of spaces to use for indentation or `tab` for tabs
- `testsDir` (default: `{spec,test,tests}`): directory where test files are located.
  Example: `src` for single directory, `{spec,tests}` to include multiple directories.
  In addition, files in `__tests__` folders and files with `*.spec.*`/`*.test.*` filenames are picked up as test files, even outside of `testsDir`.
- `cypress` (default: `false`): enable Cypress-specific rules
- `jest` (default: `false`): enable Jest-specific rules
- `mocha` (default: `false`): enable Mocha-specific rules
- `react` (default: `false`): enable React-specific rules
- `vitest` (default: `false`): enable Vitest-specific rules

The function returns an array of ESLint "[Flat Config](https://eslint.org/docs/v8.x/use/configure/configuration-files-new)" objects.
You may further customize the default configuration by adding your own configuration objects to the exported array.

```js
const eslint = require('@ovos-media/coding-standard/eslint');

module.exports = [
  ...eslint({ react: true, vitest: true }),
  // your custom config and overrides
  {
    ignores: ['public'],
  },
  {
    rules: {
      // toggle off unwanted rules
      'import/order': 'off',
    },
  },
  {
    files: ['**/*.?(m|c)[jt]s?(x)'],
    rules: {
      // your custom rules
    },
  },
];
```

---

### `prettier.config.js`

```js
module.exports = require('@ovos-media/coding-standard').prettier;
```

### CODE REVIEW

**Comment by falkenhawk** [comment]
Published as [v2.0.0-rc.0](https://www.npmjs.com/package/@ovos-media/coding-standard/v/2.0.0-rc.0)

**Review by flipace — APPROVED** [review]
wow, you went into a lot of detail also with the comments - thank you 🙏

**Review by denisLoncaric — APPROVED** [review]

**Review by marcinlee — APPROVED** [review]
Solid work :+1: Thank you :bow:

**Review by visuallization — APPROVED** [review]

**Comment by falkenhawk** [comment]
[v2.0.0-rc.1](https://www.npmjs.com/package/@ovos-media/coding-standard/v/2.0.0-rc.1) published with new options to customize eslint:

- `disableTypeChecked`: List ts files which should be linted, but are not covered by `tsconfig.json` 
  to avoid `Parsing error (...) TSConfig does not include this file`. [read more &raquo;](https://typescript-eslint.io/linting/troubleshooting/#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file)
  Example: `['dangerfile.ts', '.storybook/*.ts?(x)']`
- `mocha` (default: `false`): enable Mocha-specific rules

**Comment by falkenhawk** [comment]
[v2.0.0-rc.2](https://www.npmjs.com/package/@ovos-media/coding-standard/v/2.0.0-rc.2) published with new options to customize eslint:

- `testsDir` (default: `spec`): directory where test files are located. Can be also configured as `{spec,tests}` to include multiple directories.
  In addition, files in `__tests__` folders and files with `*.spec.*`/`*.test.*` filenames are picked up as test files, even outside of `testsDir`.
- `cypress` (default: `false`): enable Cypress-specific rules

**Pull request merged**
